import { LinkedList } from "./linkedList.js";

const list = new LinkedList();
console.log(list.size());
list.append("dog");
list.append("cat");
list.append("parrot");
list.append("hamster");
list.append("snake");
list.append("turtle");

console.log(list.toString());
list.insertAt(1, 10, 11);
console.log(list.toString());
console.log("Hello");
list.insertAt(0, 7, 6);
console.log(list.toString());
console.log(list.at(0));
console.log(list.at(9));
console.log(list.at(10));
list.insertAt(10, 7, 6);
console.log(list.toString());
list.removeAt(0);
console.log(list.toString());
list.removeAt(1);
console.log(list.toString());
list.removeAt(9);
console.log(list.toString());
list.removeAt(5);
console.log(list.toString());
